/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

import proyecto2.Pelicula;
import modelo.Movies;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.awt.image.BufferedImage;
import java.time.LocalDate;

/**
 *
 * @author ESTUDIANTE
 */
public class Interfaz extends javax.swing.JFrame {
 private Movies movies;
    
 
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        movies = new Movies();
        
    }
private void mostrarPeliculasEnInterfaz(ArrayList<Pelicula> peliculas) {
   
    
    StringBuilder peliculasTexto = new StringBuilder();
    
    for (Pelicula pelicula : peliculas) {
        // Obtener el título original (si está disponible en la clase Pelicula)
        String originalTitle = pelicula.getOriginalTitle(); // Asumiendo que existe este método
        
        // Obtener la ruta del póster (si está disponible en la clase Pelicula)
        String posterPath = pelicula.getPosterPath(); // Asumiendo que existe este método
        
        // Construir el texto con la información de cada película
        peliculasTexto.append("Título: ").append(pelicula.getTitulo()).append("\n");
        
        // Agregar el título original si está disponible
        if (originalTitle != null && !originalTitle.isEmpty()) {
            peliculasTexto.append("Título Original: ").append(originalTitle).append("\n");
        }
      
            peliculasTexto.append("Ruta del Póster: ").append(posterPath).append("\n");
        
        peliculasTexto.append("Resumen: ").append(pelicula.getOverview()).append("\n");
        int year = pelicula.getReleaseDate().getYear();
      peliculasTexto.append("Año: ").append(year).append("\n");
        peliculasTexto.append("\n");
    }
    
    // Colocar el texto en el JTextArea
    jTextArea1.setText(peliculasTexto.toString());
    
    // Colocar el JTextArea en el JScrollPane
    jScrollPane1.setViewportView(jTextArea1);
}

private ArrayList<Pelicula> buscarPeliculas(String textoBusqueda, String tipoBusqueda) {
    ArrayList<Pelicula> peliculas = movies.obtenerPeliculas();
    ArrayList<Pelicula> peliculasEncontradas = new ArrayList<>();
    
    for (Pelicula pelicula : peliculas) {
        String valorBuscado = "";
        // Determinar qué campo de la película se usará para la búsqueda
        switch (tipoBusqueda) {
            case "Titulo":
                valorBuscado = pelicula.getTitulo();
                break;
            case "Id":
                
                break;
            case "Año":
               int añoBuscado = Integer.parseInt(textoBusqueda); // Convertir el texto de búsqueda a entero
    int añoPelicula = pelicula.getReleaseDate().getYear(); // Obtener el año de la película
    
    if (añoPelicula == añoBuscado) { // Comparar el año de la película con el año buscado
        peliculasEncontradas.add(pelicula);
    }
               
                break;
            // Puedes agregar más casos según los campos disponibles en tu clase Pelicula
        }
        
        // Realizar la comparación para ver si coincide con el texto de búsqueda
        if (valorBuscado != null && valorBuscado.toLowerCase().contains(textoBusqueda.toLowerCase())) {
            peliculasEncontradas.add(pelicula);
        }
    }
    
    return peliculasEncontradas;
}
// Método para cargar la imagen desde la ruta o URL proporcionada


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCollage = new javax.swing.JLabel();
        bntBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        cmbTiposdeBusqueda = new javax.swing.JComboBox<>();
        lblTipoBusqueda = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        lblImagenLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/Logo3.1.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MoviePrime");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblImagenLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(lblImagenLogo)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 710));

        lblCollage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/collage 6.png"))); // NOI18N
        jPanel1.add(lblCollage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 420, 710));

        bntBuscar.setBackground(new java.awt.Color(204, 204, 204));
        bntBuscar.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(bntBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 110, 40));
        bntBuscar.getAccessibleContext().setAccessibleName("btnBuscar");

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Buscar pelicula");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 320, 30));
        txtBuscar.getAccessibleContext().setAccessibleName("buscarTxt");

        cmbTiposdeBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Genero", "Año" }));
        jPanel1.add(cmbTiposdeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 120, 40));

        lblTipoBusqueda.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        lblTipoBusqueda.setText("Tipo de Busqueda");
        jPanel1.add(lblTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, 40));

        lblTitulo.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        lblTitulo.setText("MoviePrime");
        lblTitulo.setToolTipText("");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 260, 70));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 520, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        txtBuscar.setText("");
        txtBuscar.setForeground (Color.black); 
        
    }//GEN-LAST:event_txtBuscarMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
       String textoBusqueda = txtBuscar.getText();
    String tipoBusqueda = (String) cmbTiposdeBusqueda.getSelectedItem();

    ArrayList<Pelicula> peliculasEncontradas = buscarPeliculas(textoBusqueda, tipoBusqueda);
    
    mostrarPeliculasEnInterfaz(peliculasEncontradas);
    }//GEN-LAST:event_bntBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JComboBox<String> cmbTiposdeBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCollage;
    private javax.swing.JLabel lblImagenLogo;
    private javax.swing.JLabel lblTipoBusqueda;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables


}
